stages:
  data_ingestion:
    cmd: python src\cnn_Classifier\pipeline\stage_01_data_ingestion.py
    deps:
      - src\cnn_Classifier\pipeline\stage_01_data_ingestion.py
      - config\config.yaml
    outs:
      - artifacts\data_ingestion\Data

  prepare_base_model:
    cmd: python src\cnn_Classifier\pipeline\stage_02_base_model.py
    deps:
      - src\cnn_Classifier\pipeline\stage_02_base_model.py
      - config\config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHT
      - LEARNING_RATE
    outs:
      - artifacts\prepare_base_model

  training:
    cmd: python src\cnn_Classifier\pipeline\stage_03_model_trainer.py
    deps:
      - src\cnn_Classifier\pipeline\stage_03_model_trainer.py
      - config\config.yaml
      - artifacts\data_ingestion\Data
      - artifacts\prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts\training\model.keras

  evaluation:
    cmd: python src\cnn_Classifier\pipeline\stage_04_mode_eval.py
    deps:
      - src\cnn_Classifier\pipeline\stage_04_mode_eval.py
      - config\config.yaml
      - artifacts\data_ingestion\Data
      - artifacts\training\model.keras
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: False
